# -*- coding: utf-8 -*-
"""Board

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sd3FVInxFc8fgWxsWMuiivSM1Fl6u2g7
"""

def print_board():
  board =[['-','-','-'],
        ['-','-','-'],
        ['-','-','-']]

  for i in range(len(board)):
     print(board[i])

print_board()