# -*- coding: utf-8 -*-
"""Board.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qtvUiCIcqDByZooN5NXGaJcL7_fqxSgX
"""

#define variables area
board =[['-','-','-'],
        ['-','-','-'],
        ['-','-','-']]
row = int()
col = int()
player = 0

def print_board():

  print("Printing board...")
  for j in range(len(board)):
   print(board[j])

def check_mark(row, col):
  if row > 2 or col > 2:
    return False
  elif board[int(row)][int(col)] == '-':
    return True
  elif row > 2 or col > 2:
    return False
  elif board[int(row)][int(col)] == 'X' or board[int(row)][int(col)] == 'O':
    return False

def main(row,col,player):
  num=0
  print_board()
  while num < 9:
    if num % 2 == 0:
      player = 1
      print("Player one, make your move")
      row=input(("Enter row num "))
      col=input(("Enter col num "))
      if player == 1 and check_mark(int(row),int(col)) == True:
        board[int(row)][int(col)] = 'X'
        print("Player 1 added a mark at the location "+str(row)+','+str(col))
        num+=1
        print_board()
      elif int(row) > 2 or int(col) > 2:
        print("Invalid row or column. Please select row / col between values 0 to 2")
        print("Invalid choice, please try again")
      elif check_mark(int(row),int(col)) == False and player == 1:
        print("Board["+str(row)+"]"+"["+str(col)+"]"+"has already been selected. Please try somewhere else on the board")
        print("Invalid choice, please try again")      
    else:
      player = 2
      print("Player two, make your move")
      row=input(("Enter row num "))
      col=input(("Enter col num "))
      if player == 2 and check_mark(int(row),int(col)) == True:
        board[int(row)][int(col)] = 'O'      
        print("Player 2 added a mark at the location "+str(row)+','+str(col))
        num+=1
        print_board()
      elif int(row) > 2 or int(col) > 2:
        print("Invalid row or column. Please select row / col between values 0 to 2")
        print("Invalid choice, please try again")
      elif check_mark(int(row),int(col)) == False and player == 2:
        print("Board["+str(row)+"]"+"["+str(col)+"]"+"has already been selected. Please try somewhere else on the board")
        print("Invalid choice, please try again")

main(row,col,player)